# Generated by Django 4.2.7 on 2026-09-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_betting', '0022_alter_cronschedule_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veredicto', models.CharField(choices=[('OK', 'Legítima (resultado coincide con los datos)'), ('REVISAR', 'Posible liquidación incorrecta — revisión manual'), ('NO_VERIFICABLE', 'No verificable (evidencia insuficiente)')], max_length=15, verbose_name='Veredicto')),
                ('direccion', models.CharField(blank=True, choices=[('perdida_dudosa', 'Posible pérdida mal liquidada'), ('victoria_dudosa', 'Posible victoria mal liquidada (sobre-pago)')], default='', max_length=20, verbose_name='Dirección de la discrepancia')),
                ('estado_kambi', models.CharField(blank=True, default='', max_length=10, verbose_name='Estado BetPlay')),
                ('estado_esperado', models.CharField(blank=True, default='', max_length=10, verbose_name='Estado según datos')),
                ('confianza', models.CharField(blank=True, default='', max_length=10, verbose_name='Confianza del match')),
                ('detalle', models.CharField(blank=True, default='', max_length=400, verbose_name='Detalle de la verificación')),
                ('fixture_api_id', models.IntegerField(blank=True, null=True, verbose_name='Fixture API-Football')),
                ('fuente', models.CharField(blank=True, default='API-Football', max_length=60, verbose_name='Fuente de datos')),
                ('reintentos', models.PositiveIntegerField(default=0, verbose_name='Reintentos de verificación')),
                ('intentos_aviso', models.PositiveIntegerField(default=0, verbose_name='Intentos de aviso (usuario)')),
                ('intentos_aviso_admin', models.PositiveIntegerField(default=0, verbose_name='Intentos de aviso (admin)')),
                ('aviso_usuario', models.BooleanField(default=False, verbose_name='Usuario avisado')),
                ('aviso_admin', models.BooleanField(default=False, verbose_name='Admin avisado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('apuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion', to='auto_betting.historialapuesta', verbose_name='Apuesta')),
            ],
            options={
                'verbose_name': 'Inspección de apuesta',
                'verbose_name_plural': 'Inspecciones de apuestas',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['veredicto', '-creado'], name='inspector_i_veredic_f68caf_idx'), models.Index(fields=['-creado'], name='inspector_i_creado_e6512d_idx')],
            },
        ),
    ]
