# Generated by Django 4.2.7 on 2026-09-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionapuesta',
            name='margen',
            field=models.FloatField(blank=True, null=True, verbose_name='Margen |valor-línea| (None=sin línea)'),
        ),
    ]
