# Generated by Django 4.2.7 on 2026-09-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_inspeccionapuesta_margen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccionapuesta',
            name='aviso_admin',
        ),
        migrations.RemoveField(
            model_name='inspeccionapuesta',
            name='intentos_aviso_admin',
        ),
        migrations.AlterField(
            model_name='inspeccionapuesta',
            name='intentos_aviso',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos de aviso'),
        ),
    ]
