# Generated by Django 4.2.7 on 2026-09-01 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('FIJO', 'Stake fijo (lo defino yo)'), ('COMPUESTO', 'Interés compuesto (% del balance)')], default='FIJO', max_length=10, verbose_name='Modo de gestión del stake')),
                ('porcentaje', models.FloatField(default=2.0, verbose_name='% del balance por apuesta')),
                ('balance_inicial', models.BigIntegerField(blank=True, null=True, verbose_name='Balance declarado (COP)')),
                ('ancla', models.DateTimeField(blank=True, null=True, verbose_name='Ancla de activación')),
                ('stake_min_cop', models.IntegerField(default=500, verbose_name='Stake mínimo (COP)')),
                ('stake_max_cop', models.IntegerField(default=5000, verbose_name='Stake máximo (COP)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_config', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de capital',
                'verbose_name_plural': 'Configuraciones de capital',
            },
        ),
        migrations.CreateModel(
            name='CapitalAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_cop', models.BigIntegerField(verbose_name='Monto del ajuste (COP, firmado)')),
                ('motivo', models.CharField(default='Ajuste manual', max_length=255, verbose_name='Motivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_ajustes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ajuste de capital',
                'verbose_name_plural': 'Ajustes de capital',
                'ordering': ['-fecha'],
            },
        ),
    ]
