# Generated by Django 4.2.7 on 2026-09-02 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalLegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_ref', models.BigIntegerField(verbose_name='Coupon ref de la apuesta legada')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_legadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Apuesta legada (OPEN al activar)',
                'verbose_name_plural': 'Apuestas legadas (OPEN al activar)',
                'unique_together': {('usuario', 'coupon_ref')},
            },
        ),
    ]
