# Generated by Django 4.2.7 on 2026-09-02 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Interruptor maestro: si se apaga, nadie recibe avisos de WhatsApp.', verbose_name='Notificaciones activas')),
            ],
            options={
                'verbose_name': 'Configuración de notificaciones',
                'verbose_name_plural': 'Configuración de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('destino', models.CharField(blank=True, default='', max_length=30)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERROR', 'Error'), ('OMITIDO', 'Omitido')], default='ENVIADO', max_length=10)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacion_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de notificación',
                'verbose_name_plural': 'Logs de notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, default='', max_length=30)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_estados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de notificación',
                'verbose_name_plural': 'Estados de notificación',
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
