# Generated by Django 4.2.7 on 2026-08-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='Ticket de login BetPlay')),
                ('punter_id', models.CharField(default='2585240', max_length=50, verbose_name='Punter ID')),
                ('edge_minimo', models.FloatField(default=5.0, verbose_name='Edge mínimo (%)')),
                ('odds_minima', models.FloatField(default=1.5, verbose_name='Odds mínima')),
                ('stake', models.IntegerField(default=500000, verbose_name='Stake (en unidades Kambi, 500000=500 COP)')),
                ('max_apuestas_diarias', models.IntegerField(default=5, verbose_name='Máximo de apuestas por día')),
                ('horas_adelante', models.IntegerField(default=24, verbose_name='Horas hacia adelante para escanear')),
                ('activo', models.BooleanField(default=True, verbose_name='Sistema activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Auto-Betting',
                'verbose_name_plural': 'Configuración Auto-Betting',
            },
        ),
        migrations.CreateModel(
            name='DailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('apuestas_colocadas', models.IntegerField(default=0, verbose_name='Apuestas colocadas')),
            ],
            options={
                'verbose_name': 'Contador Diario',
                'verbose_name_plural': 'Contadores Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AutoBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.BigIntegerField(verbose_name='Event ID (Kambi)')),
                ('home_team', models.CharField(max_length=200, verbose_name='Equipo Local')),
                ('away_team', models.CharField(max_length=200, verbose_name='Equipo Visitante')),
                ('liga', models.CharField(max_length=200, verbose_name='Liga')),
                ('start_time', models.DateTimeField(verbose_name='Inicio del partido')),
                ('mercado', models.CharField(max_length=100, verbose_name='Mercado')),
                ('seleccion', models.CharField(max_length=100, verbose_name='Selección')),
                ('linea', models.FloatField(blank=True, null=True, verbose_name='Línea')),
                ('cuota', models.FloatField(verbose_name='Cuota jugada')),
                ('corners_predichos', models.FloatField(verbose_name='Córners predichos')),
                ('predicta_prob', models.FloatField(verbose_name='Probabilidad Predicta (%)')),
                ('edge', models.FloatField(verbose_name='Edge (%)')),
                ('ev', models.FloatField(verbose_name='EV')),
                ('coupon_ref', models.BigIntegerField(blank=True, null=True, verbose_name='Coupon Ref')),
                ('bet_ref', models.BigIntegerField(blank=True, null=True, verbose_name='Bet Ref')),
                ('stake', models.IntegerField(default=500000, verbose_name='Stake (Kambi)')),
                ('potential_payout', models.BigIntegerField(blank=True, null=True, verbose_name='Pago potencial')),
                ('estado', models.CharField(choices=[('OPEN', 'Abierta'), ('WIN', 'Ganada'), ('LOSE', 'Perdida'), ('VOID', 'Anulada'), ('CASHOUT', 'Cashout'), ('ERROR', 'Error')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apuesta Automática',
                'verbose_name_plural': 'Apuestas Automáticas',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['-creado'], name='auto_bettin_creado_f119f5_idx'), models.Index(fields=['evento_id', 'mercado'], name='auto_bettin_evento__9956c8_idx')],
            },
        ),
    ]
