# Generated by Django 4.2.7 on 2026-08-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autobetconfig',
            name='edge_minimo',
        ),
        migrations.AddField(
            model_name='autobetconfig',
            name='cuota_minima',
            field=models.FloatField(default=2.0, verbose_name='Cuota mínima (>)'),
        ),
    ]
