# Generated by Django 4.2.7 on 2026-08-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0002_remove_autobetconfig_edge_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_ref', models.BigIntegerField(unique=True, verbose_name='Coupon Ref')),
                ('coupon_external_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='External Ref')),
                ('placed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha colocada')),
                ('bet_ref', models.BigIntegerField(blank=True, null=True, verbose_name='Bet Ref')),
                ('bet_odds', models.FloatField(blank=True, null=True, verbose_name='Cuota (decimal)')),
                ('played_odds', models.FloatField(blank=True, null=True, verbose_name='Cuota jugada (decimal)')),
                ('bet_status', models.CharField(default='OPEN', max_length=10, verbose_name='Estado (Kambi)')),
                ('stake', models.IntegerField(default=0, verbose_name='Stake (unidades Kambi)')),
                ('payout', models.BigIntegerField(default=0, verbose_name='Payout (unidades Kambi)')),
                ('potential_payout', models.BigIntegerField(default=0, verbose_name='Payout potencial')),
                ('outcome_id', models.BigIntegerField(blank=True, null=True, verbose_name='Outcome ID')),
                ('event_id', models.BigIntegerField(blank=True, null=True, verbose_name='Event ID')),
                ('home_team', models.CharField(blank=True, default='', max_length=200, verbose_name='Local')),
                ('away_team', models.CharField(blank=True, default='', max_length=200, verbose_name='Visitante')),
                ('event_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del partido')),
                ('seleccion', models.CharField(blank=True, default='', max_length=200, verbose_name='Selección')),
                ('mercado', models.CharField(blank=True, default='', max_length=250, verbose_name='Mercado')),
                ('linea', models.FloatField(blank=True, null=True, verbose_name='Línea')),
                ('sport', models.CharField(blank=True, default='', max_length=50, verbose_name='Deporte')),
                ('liga', models.CharField(blank=True, default='', max_length=200, verbose_name='Liga')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historial de Apuesta',
                'verbose_name_plural': 'Historial de Apuestas',
                'ordering': ['-placed_date'],
                'indexes': [models.Index(fields=['-placed_date'], name='auto_bettin_placed__ee7f5b_idx'), models.Index(fields=['bet_status'], name='auto_bettin_bet_sta_f73ccf_idx')],
            },
        ),
    ]
