# Generated by Django 4.2.7 on 2026-08-19 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_betting', '0004_clv_is_system_oddssnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historialapuesta',
            new_name='auto_bettin_is_syst_d6d74e_idx',
            old_name='auto_bet_is_sys_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialapuesta',
            new_name='auto_bettin_outcome_f6da9b_idx',
            old_name='auto_bet_outcome_place_idx',
        ),
        migrations.RenameIndex(
            model_name='oddssnapshot',
            new_name='auto_bettin_outcome_5a1aef_idx',
            old_name='oddssnap_outcome_capt_idx',
        ),
        migrations.RenameIndex(
            model_name='oddssnapshot',
            new_name='auto_bettin_event_i_10914f_idx',
            old_name='oddssnap_event_id_idx',
        ),
        migrations.AddField(
            model_name='autobet',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_bets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='autobetconfig',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_bet_config', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='dailycounter',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_counters', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historialapuesta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_apuestas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='dailycounter',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historialapuesta',
            name='coupon_ref',
            field=models.BigIntegerField(verbose_name='Coupon Ref'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycounter',
            unique_together={('usuario', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='historialapuesta',
            unique_together={('usuario', 'coupon_ref')},
        ),
    ]
