# Generated by Django 4.2.7 on 2026-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0007_usuario_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobetconfig',
            name='punter_id',
            field=models.CharField(default='', max_length=50, verbose_name='Punter ID'),
        ),
    ]
