# Generated by Django 4.2.7 on 2026-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0008_alter_autobetconfig_punter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobetconfig',
            name='max_apuestas_diarias',
            field=models.IntegerField(default=20, verbose_name='Máximo de apuestas por día'),
        ),
    ]
