# Generated by Django 4.2.7 on 2026-08-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0009_alter_autobetconfig_max_apuestas_diarias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_over_min_p', models.FloatField(default=0.5, verbose_name='Goles Over — P mínima')),
                ('goals_over_min_confidence', models.FloatField(default=0.35, verbose_name='Goles Over — Confianza mínima')),
                ('goals_under_min_p', models.FloatField(default=0.5, verbose_name='Goles Under — P mínima')),
                ('goals_under_min_confidence', models.FloatField(default=0.35, verbose_name='Goles Under — Confianza mínima')),
                ('corners_over_min_p', models.FloatField(default=0.56, verbose_name='Córners Over — P mínima')),
                ('corners_over_min_confidence', models.FloatField(default=0.35, verbose_name='Córners Over — Confianza mínima')),
                ('corners_under_min_p', models.FloatField(default=0.56, verbose_name='Córners Under — P mínima')),
                ('corners_under_min_confidence', models.FloatField(default=0.35, verbose_name='Córners Under — Confianza mínima')),
                ('shots_on_target_over_min_p', models.FloatField(default=0.56, verbose_name='Tiros a puerta Over — P mínima')),
                ('shots_on_target_over_min_confidence', models.FloatField(default=0.35, verbose_name='Tiros a puerta Over — Confianza mínima')),
                ('shots_on_target_under_min_p', models.FloatField(default=0.56, verbose_name='Tiros a puerta Under — P mínima')),
                ('shots_on_target_under_min_confidence', models.FloatField(default=0.35, verbose_name='Tiros a puerta Under — Confianza mínima')),
                ('btts_si_min_p', models.FloatField(default=0.5, verbose_name='BTTS Sí — P mínima')),
                ('btts_si_min_confidence', models.FloatField(default=0.35, verbose_name='BTTS Sí — Confianza mínima')),
                ('btts_no_min_p', models.FloatField(default=0.5, verbose_name='BTTS No — P mínima')),
                ('btts_no_min_confidence', models.FloatField(default=0.35, verbose_name='BTTS No — Confianza mínima')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=200, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Umbrales por Submercado',
                'verbose_name_plural': 'Configuración de Umbrales por Submercado',
            },
        ),
    ]
