# Generated by Django 4.2.7 on 2026-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0010_marketfilterconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketfilterconfig',
            name='btts_no_enabled',
            field=models.BooleanField(default=False, verbose_name='BTTS No — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='btts_no_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='BTTS No — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='btts_no_min_ev',
            field=models.FloatField(default=0.0, verbose_name='BTTS No — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='btts_si_enabled',
            field=models.BooleanField(default=True, verbose_name='BTTS Sí — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='btts_si_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='BTTS Sí — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='btts_si_min_ev',
            field=models.FloatField(default=0.0, verbose_name='BTTS Sí — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='calib_cap',
            field=models.FloatField(default=0.58, help_text='Cap duro de probabilidad calibrada. La auditoría muestra anti-señal arriba de 0.60.', verbose_name='Cap de calibración de probabilidad'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='corners_over_enabled',
            field=models.BooleanField(default=True, verbose_name='Córners Over — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='corners_over_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Córners Over — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='corners_over_min_ev',
            field=models.FloatField(default=0.2, verbose_name='Córners Over — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='corners_under_enabled',
            field=models.BooleanField(default=False, verbose_name='Córners Under — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='corners_under_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Córners Under — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='corners_under_min_ev',
            field=models.FloatField(default=0.0, verbose_name='Córners Under — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='cuota_minima_global',
            field=models.FloatField(default=2.5, help_text='Piso de cuota para TODO el sistema. Reemplaza el 2.0 per-user.', verbose_name='Cuota mínima global'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='goals_over_enabled',
            field=models.BooleanField(default=True, verbose_name='Goles Over — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='goals_over_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Goles Over — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='goals_over_min_ev',
            field=models.FloatField(default=0.15, verbose_name='Goles Over — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='goals_under_enabled',
            field=models.BooleanField(default=True, verbose_name='Goles Under — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='goals_under_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Goles Under — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='goals_under_min_ev',
            field=models.FloatField(default=0.0, verbose_name='Goles Under — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='max_exposicion_evento_cop',
            field=models.FloatField(default=20000.0, help_text='Tope de stake combinado (todas las cuentas) por evento+mercado. 0 = desactivado.', verbose_name='Máx. exposición por evento/mercado (COP)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_over_enabled',
            field=models.BooleanField(default=True, verbose_name='Tiros a puerta Over — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_over_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Tiros a puerta Over — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_over_min_ev',
            field=models.FloatField(default=0.0, verbose_name='Tiros a puerta Over — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_under_enabled',
            field=models.BooleanField(default=True, verbose_name='Tiros a puerta Under — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_under_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Tiros a puerta Under — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_under_min_ev',
            field=models.FloatField(default=0.0, verbose_name='Tiros a puerta Under — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='stop_loss_diario_cop',
            field=models.FloatField(default=-30000.0, help_text='Si el P&L del día (solo sistema) baja de esto, se detiene el auto-betting. 0 = desactivado.', verbose_name='Stop-loss diario (COP)'),
        ),
        migrations.AlterField(
            model_name='marketfilterconfig',
            name='btts_si_min_p',
            field=models.FloatField(default=0.52, verbose_name='BTTS Sí — P mínima'),
        ),
        migrations.AlterField(
            model_name='marketfilterconfig',
            name='goals_under_min_p',
            field=models.FloatField(default=0.54, verbose_name='Goles Under — P mínima'),
        ),
    ]
