# Generated by Django 4.2.7 on 2026-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0011_marketfilterconfig_btts_no_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobet',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confianza (%)'),
        ),
    ]
