# Generated by Django 4.2.7 on 2026-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0012_add_confidence_to_autobet'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_over_max_line',
            field=models.FloatField(default=0.0, verbose_name='Tiros a puerta Over — Línea máxima (0=sin tope)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_over_min_line',
            field=models.FloatField(default=0.0, verbose_name='Tiros a puerta Over — Línea mínima'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_under_max_line',
            field=models.FloatField(default=0.0, verbose_name='Tiros a puerta Under — Línea máxima (0=sin tope)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='shots_on_target_under_min_line',
            field=models.FloatField(default=9.5, verbose_name='Tiros a puerta Under — Línea mínima'),
        ),
    ]
