# Generated by Django 4.2.7 on 2026-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0013_marketfilterconfig_shots_on_target_over_max_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobet',
            name='predicta_prob_raw',
            field=models.FloatField(blank=True, null=True, verbose_name='Probabilidad cruda (%)'),
        ),
    ]
