# Generated by Django 4.2.7 on 2026-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0014_autobet_predicta_prob_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(choices=[('api_football_daily', 'Sync diario API-Football (sync_daily + populate_legacy)'), ('sync_bet_history', 'Sync de resultados desde Kambi (bet_status)'), ('calibration_report', 'Reporte de calibración (WR real vs P declarada)'), ('run_auto_bets', 'Auto-betting (colocar apuestas)'), ('capture_closing_odds', 'Captura de cuotas de cierre (CLV)'), ('sync_bet_history_vespertino', 'Sync vespertino de resultados'), ('api_football_backfill', 'Backfill 2 temporadas (reset cuota 00:00 UTC)'), ('check_betplay_tokens', 'Verificación de tickets BetPlay')], max_length=64, unique=True, verbose_name='Tarea')),
                ('hora_utc', models.IntegerField(verbose_name='Hora UTC (0-23)')),
                ('minuto_utc', models.IntegerField(default=0, verbose_name='Minuto UTC (0-59)')),
                ('cada_n_minutos', models.IntegerField(default=0, verbose_name='Repetir cada N minutos (0=solo a la hora fija)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción')),
                ('ultimo_run', models.DateTimeField(blank=True, null=True, verbose_name='Último ejecución')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=200, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Horario de Cron',
                'verbose_name_plural': 'Horarios de Cron',
                'ordering': ['hora_utc', 'minuto_utc'],
            },
        ),
    ]
