# Generated by Django 4.2.7 on 2026-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0015_cron_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobetconfig',
            name='ticket_actualizado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket actualizado el'),
        ),
    ]
