# Generated by Django 4.2.7 on 2026-09-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0016_ticket_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_over_enabled',
            field=models.BooleanField(default=True, verbose_name='Remates totales Over — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_over_max_line',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Over — Línea máxima (0=sin tope)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_over_min_confidence',
            field=models.FloatField(default=0.35, verbose_name='Remates totales Over — Confianza mínima'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_over_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Over — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_over_min_ev',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Over — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_over_min_line',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Over — Línea mínima'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_over_min_p',
            field=models.FloatField(default=0.5, verbose_name='Remates totales Over — P mínima'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_under_enabled',
            field=models.BooleanField(default=True, verbose_name='Remates totales Under — Activo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_under_max_line',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Under — Línea máxima (0=sin tope)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_under_min_confidence',
            field=models.FloatField(default=0.35, verbose_name='Remates totales Under — Confianza mínima'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_under_min_cuota',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Under — Cuota mínima (0=usa global)'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_under_min_ev',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Under — EV mínimo'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_under_min_line',
            field=models.FloatField(default=0.0, verbose_name='Remates totales Under — Línea mínima'),
        ),
        migrations.AddField(
            model_name='marketfilterconfig',
            name='remates_under_min_p',
            field=models.FloatField(default=0.5, verbose_name='Remates totales Under — P mínima'),
        ),
    ]
