# Generated by Django 4.2.7 on 2026-09-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0017_marketfilterconfig_remates_over_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcasePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=200, verbose_name='Equipo local')),
                ('away_team', models.CharField(max_length=200, verbose_name='Equipo visitante')),
                ('liga', models.CharField(max_length=200, verbose_name='Liga')),
                ('start_time', models.DateTimeField(verbose_name='Inicio del partido (UTC)')),
                ('mercado', models.CharField(max_length=100, verbose_name='Mercado')),
                ('seleccion', models.CharField(max_length=120, verbose_name='Selección')),
                ('linea', models.FloatField(blank=True, null=True, verbose_name='Línea')),
                ('cuota', models.FloatField(verbose_name='Cuota de mercado (BetPlay)')),
                ('cuota_justa', models.FloatField(blank=True, null=True, verbose_name='Cuota justa (1/P del modelo)')),
                ('fair_odds', models.FloatField(blank=True, null=True, verbose_name='Cuota justa devig (referencia)')),
                ('prob', models.FloatField(blank=True, null=True, verbose_name='Probabilidad calibrada (%)')),
                ('prob_raw', models.FloatField(blank=True, null=True, verbose_name='Probabilidad sin calibrar (%)')),
                ('prob_mercado', models.FloatField(blank=True, null=True, verbose_name='Probabilidad implícita de mercado (%)')),
                ('edge', models.FloatField(blank=True, null=True, verbose_name='Edge vs cuota de mercado (%)')),
                ('ev', models.FloatField(blank=True, null=True, verbose_name='EV vs cuota justa devig (%)')),
                ('confianza', models.FloatField(blank=True, null=True, verbose_name='Confianza del modelo (0-1)')),
                ('x12_local', models.FloatField(blank=True, null=True, verbose_name='1X2 local (%)')),
                ('x12_empate', models.FloatField(blank=True, null=True, verbose_name='1X2 empate (%)')),
                ('x12_visita', models.FloatField(blank=True, null=True, verbose_name='1X2 visitante (%)')),
                ('evento_id', models.BigIntegerField(blank=True, null=True, verbose_name='Evento Kambi')),
                ('generado', models.DateTimeField(auto_now_add=True, verbose_name='Generado')),
            ],
            options={
                'verbose_name': 'Partido destacado de la portada',
                'verbose_name_plural': 'Partidos destacados de la portada',
                'ordering': ['-generado'],
            },
        ),
    ]
