# Generated by Django 4.2.7 on 2026-09-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0018_showcasepick'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('evento_id', models.CharField(blank=True, max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('home_team', models.CharField(blank=True, max_length=120)),
                ('away_team', models.CharField(blank=True, max_length=120)),
                ('liga', models.CharField(blank=True, max_length=120)),
                ('mercado', models.CharField(max_length=120)),
                ('motor', models.CharField(blank=True, max_length=40)),
                ('seleccion', models.CharField(max_length=120)),
                ('linea', models.FloatField(blank=True, null=True)),
                ('cuota', models.FloatField(blank=True, null=True)),
                ('prob', models.FloatField(blank=True, null=True)),
                ('ev', models.FloatField(blank=True, null=True)),
                ('stake', models.IntegerField(default=10000)),
                ('estado', models.CharField(choices=[('OPEN', 'Pendiente'), ('WON', 'Ganada'), ('LOST', 'Perdida'), ('VOID', 'Anulada')], db_index=True, default='OPEN', max_length=8)),
                ('resultado_real', models.CharField(blank=True, max_length=20)),
                ('payout', models.FloatField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apuesta paper',
                'verbose_name_plural': 'Apuestas paper',
                'indexes': [models.Index(fields=['estado', 'motor'], name='auto_bettin_estado_0d8853_idx')],
            },
        ),
    ]
