# Generated by Django 4.2.7 on 2026-09-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0019_paperbet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperParlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('legs', models.JSONField(default=list)),
                ('cuota', models.FloatField(blank=True, null=True)),
                ('prob', models.FloatField(blank=True, null=True)),
                ('ev', models.FloatField(blank=True, null=True)),
                ('stake', models.IntegerField(default=10000)),
                ('estado', models.CharField(choices=[('OPEN', 'Pendiente'), ('WON', 'Ganada'), ('LOST', 'Perdida'), ('VOID', 'Anulada')], db_index=True, default='OPEN', max_length=8)),
                ('resultado_real', models.CharField(blank=True, max_length=40)),
                ('payout', models.FloatField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Combinada paper',
                'verbose_name_plural': 'Combinadas paper',
            },
        ),
    ]
