# Generated by Django 4.2.7 on 2026-09-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0020_paperparlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbet',
            name='closing_odds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
