# Generated by Django 4.2.7 on 2026-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0021_paperbet_closing_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronschedule',
            name='tarea',
            field=models.CharField(choices=[('api_football_daily', 'Sync diario API-Football (sync_daily + populate_legacy)'), ('sync_bet_history', 'Sync de resultados desde Kambi (bet_status)'), ('calibration_report', 'Reporte de calibración (WR real vs P declarada)'), ('run_auto_bets', 'Auto-betting (colocar apuestas)'), ('capture_closing_odds', 'Captura de cuotas de cierre (CLV)'), ('sync_bet_history_vespertino', 'Sync vespertino de resultados'), ('api_football_backfill', 'Backfill 2 temporadas (reset cuota 00:00 UTC)'), ('check_betplay_tokens', 'Verificación de tickets BetPlay'), ('inspect_bets', 'Inspector de apuestas (verificación de liquidaciones)')], max_length=64, unique=True, verbose_name='Tarea'),
        ),
    ]
