# Generated by Django 4.2.7 on 2026-09-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0022_alter_cronschedule_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialapuesta',
            name='coupon_legs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Patas del cupón (1=simple)'),
        ),
    ]
