# Generated by Django 4.2.7 on 2026-09-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_betting', '0023_historialapuesta_coupon_legs'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbet',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='paperbet',
            name='llm_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paperbet',
            name='llm_verdict',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
