# Generated by Django 4.2.7 on 2026-08-15 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football_data', '0004_match_both_teams_score_match_corners_1h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KambiMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kambi_event_id', models.BigIntegerField(unique=True, verbose_name='Kambi Event ID')),
                ('home_team', models.CharField(max_length=200, verbose_name='Equipo Local')),
                ('away_team', models.CharField(max_length=200, verbose_name='Equipo Visitante')),
                ('league_name_kambi', models.CharField(max_length=200, verbose_name='Liga (Kambi)')),
                ('league_path_kambi', models.CharField(max_length=300, verbose_name='Path Kambi')),
                ('start_time', models.DateTimeField(verbose_name='Inicio del partido')),
                ('sport', models.CharField(default='FOOTBALL', max_length=50, verbose_name='Deporte')),
                ('state', models.CharField(default='NOT_STARTED', max_length=30, verbose_name='Estado')),
                ('mapped_home_team', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipo mapeado (local)')),
                ('mapped_away_team', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipo mapeado (visitante)')),
                ('mapping_confidence', models.FloatField(default=0.0, verbose_name='Confianza del mapeo')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Obtenido a las')),
                ('predicta_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_data.league', verbose_name='Liga Predicta')),
            ],
            options={
                'verbose_name': 'Partido Kambi',
                'verbose_name_plural': 'Partidos Kambi',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Iniciado')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado')),
                ('status', models.CharField(choices=[('running', 'En progreso'), ('completed', 'Completado'), ('failed', 'Fallido')], default='running', max_length=20)),
                ('matches_fetched', models.IntegerField(default=0, verbose_name='Partidos obtenidos')),
                ('matches_mapped', models.IntegerField(default=0, verbose_name='Partidos mapeados')),
                ('predictions_generated', models.IntegerField(default=0, verbose_name='Predicciones generadas')),
                ('opportunities_found', models.IntegerField(default=0, verbose_name='Oportunidades encontradas')),
                ('value_bets_found', models.IntegerField(default=0, verbose_name='Value bets encontrados')),
                ('errors', models.TextField(blank=True, default='', verbose_name='Errores')),
            ],
            options={
                'verbose_name': 'Escaneo',
                'verbose_name_plural': 'Escaneos',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ValueOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=200, verbose_name='Mercado')),
                ('selection', models.CharField(max_length=100, verbose_name='Selección')),
                ('betplay_odds', models.FloatField(verbose_name='Cuota BetPlay')),
                ('betplay_implied_prob', models.FloatField(verbose_name='Prob. implícita BetPlay')),
                ('predicta_probability', models.FloatField(verbose_name='Prob. Predicta')),
                ('predicta_prediction', models.FloatField(blank=True, null=True, verbose_name='Valor predicho')),
                ('predicta_confidence', models.FloatField(default=0.0, verbose_name='Confianza')),
                ('predicta_model', models.CharField(blank=True, max_length=200, verbose_name='Modelo usado')),
                ('edge', models.FloatField(verbose_name='Edge (%)')),
                ('ev', models.FloatField(verbose_name='EV (valor esperado)')),
                ('is_value', models.BooleanField(default=False, verbose_name='¿Es value bet?')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('executed', 'Ejecutada'), ('expired', 'Expirada'), ('dismissed', 'Descartada')], default='pending', max_length=20)),
                ('line', models.FloatField(blank=True, null=True, verbose_name='Línea')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Detectada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='value_betting.kambimatch')),
            ],
            options={
                'verbose_name': 'Oportunidad de Value',
                'verbose_name_plural': 'Oportunidades de Value',
                'ordering': ['-edge', '-created_at'],
                'indexes': [models.Index(fields=['is_value', '-edge'], name='value_betti_is_valu_4098bf_idx'), models.Index(fields=['status', '-created_at'], name='value_betti_status_51c2dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='KambiBetOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kambi_offer_id', models.BigIntegerField(verbose_name='Kambi Offer ID')),
                ('criterion_label', models.CharField(max_length=200, verbose_name='Mercado')),
                ('criterion_id', models.BigIntegerField(verbose_name='Criterion ID')),
                ('offer_type', models.CharField(max_length=100, verbose_name='Tipo de oferta')),
                ('outcome_label', models.CharField(max_length=100, verbose_name='Selección')),
                ('outcome_type', models.CharField(max_length=50, verbose_name='Tipo de outcome')),
                ('odds', models.IntegerField(verbose_name='Cuota (entero Kambi)')),
                ('odds_decimal', models.FloatField(verbose_name='Cuota decimal')),
                ('line', models.FloatField(blank=True, null=True, verbose_name='Línea')),
                ('status', models.CharField(default='OPEN', max_length=30, verbose_name='Estado')),
                ('category_id', models.IntegerField(blank=True, null=True, verbose_name='Category ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Obtenido a las')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_offers', to='value_betting.kambimatch')),
            ],
            options={
                'verbose_name': 'Cuota BetPlay',
                'verbose_name_plural': 'Cuotas BetPlay',
                'ordering': ['match', 'criterion_label', 'outcome_label'],
                'indexes': [models.Index(fields=['match', 'criterion_label'], name='value_betti_match_i_8b75a0_idx')],
            },
        ),
    ]
