# Generated by Django 4.2.7 on 2026-08-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value_betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueopportunity',
            name='bet_instruction',
            field=models.CharField(default='', max_length=300, verbose_name='Instrucción de apuesta'),
        ),
    ]
