# Generated by Django 4.2.7 on 2026-08-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='Identificador usado')),
                ('success', models.BooleanField(default=False, verbose_name='Éxito')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Intento de login',
                'verbose_name_plural': 'Intentos de login',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='cuentas_log_ip_addr_e54cfb_idx')],
            },
        ),
    ]
