# Generated by Django 4.2.7 on 2026-09-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Con código de país. Ej. 573001234567. Sin teléfono no se reciben notificaciones.', max_length=20, verbose_name='Número de WhatsApp (notificaciones)'),
        ),
    ]
