# Generated by Django 4.2.7 on 2026-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0004_match_both_teams_score_match_corners_1h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='xg_away',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='xG Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='xg_home',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='xG Home'),
        ),
    ]
