# Generated by Django 4.2.7 on 2026-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0005_match_xg_away_match_xg_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='as_field',
            field=models.IntegerField(blank=True, db_column='as_field', null=True, verbose_name='Away Shots'),
        ),
    ]
