"""
Django settings for betting_bot project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (gitignored) si existe
_ENV_FILE = BASE_DIR / '.env'
if _ENV_FILE.exists():
    with open(_ENV_FILE, encoding='utf-8') as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _v = _line.split('=', 1)
                os.environ.setdefault(_k.strip(), _v.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-05hl%jnp2o6j)8)zo=u8eu9_zkk7yd8h7&w^x6xix%@y*owsu+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'predicta.com.co', 'www.predicta.com.co']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Aplicaciones del proyecto
    'cuentas',
    'odds',
    'betfair',
    'betting',
    'capital',
    'football_data',
    'football_api',
    'ai_predictions',
    'value_betting',
    'auto_betting',
    'notificaciones',
    'inspector',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'betting_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'betting_bot' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'capital.context_processors.navbar_balance',
            ],
        },
    },
]

WSGI_APPLICATION = 'betting_bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'predicta'),
        'USER': os.getenv('DB_USER', 'predicta'),
        # Credencial en .env (gitignored). Sin hardcode: el repo es público.
        'PASSWORD': os.getenv('DB_PASSWORD', os.getenv('DATABASE_PASSWORD', '')),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
        # 2026-08-31: migración SQLite -> PostgreSQL (fix 'database is locked').
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Directorios donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
AUTH_USER_MODEL = 'cuentas.Usuario'
LOGIN_URL = '/cuentas/login/'
LOGIN_REDIRECT_URL = '/cuentas/dashboard/'
LOGOUT_REDIRECT_URL = '/cuentas/login/'


# Configuración del bot de apuestas
# Configuración de Matchbook Exchange
MATCHBOOK_USERNAME = os.getenv('MATCHBOOK_USERNAME', '')
MATCHBOOK_PASSWORD = os.getenv('MATCHBOOK_PASSWORD', '')

# Configuración de The Odds API (para partidos próximos)
ODDS_API_KEY = os.getenv('ODDS_API_KEY', '9c2c101074ae4a4c3ec9b01a4d38cb6a')
APIFOOTBALL_KEY = os.getenv('APIFOOTBALL_KEY', '')
ODDS_API_BASE_URL = 'https://api.the-odds-api.com/v4'

# Configuración de Betfair
BETFAIR_APP_KEY = os.getenv('BETFAIR_APP_KEY', 'your_betfair_app_key_here')
BETFAIR_USERNAME = os.getenv('BETFAIR_USERNAME', 'your_betfair_username_here')
BETFAIR_PASSWORD = os.getenv('BETFAIR_PASSWORD', 'your_betfair_password_here')
BETFAIR_SANDBOX = os.getenv('BETFAIR_SANDBOX', 'True').lower() == 'true'
BETFAIR_CERT_DIR = os.getenv('BETFAIR_CERT_DIR', '/etc/betfair/certs/')
BETFAIR_CERT_PATH = os.getenv('BETFAIR_CERT_PATH', '/etc/betfair/certs/client-2048.crt')
BETFAIR_KEY_PATH = os.getenv('BETFAIR_KEY_PATH', '/etc/betfair/certs/client-2048.key')

# Configuración del bot
SPORT_KEY = os.getenv('SPORT_KEY', 'soccer_germany_bundesliga')
REGIONS = os.getenv('REGIONS', 'uk,us,eu')
MARKETS = os.getenv('MARKETS', 'h2h')
ODDS_FORMAT = os.getenv('ODDS_FORMAT', 'decimal')

# Ligas y competiciones objetivo
TARGET_SPORT_KEYS = [
    sport.strip() for sport in os.getenv('TARGET_SPORT_KEYS', SPORT_KEY).split(',')
    if sport.strip()
]
BETFAIR_COMPETITION_IDS = [
    comp.strip() for comp in os.getenv('BETFAIR_COMPETITION_IDS', '').split(',')
    if comp.strip()
]
BETFAIR_COMPETITION_NAMES = [
    name.strip() for name in os.getenv('BETFAIR_COMPETITION_NAMES', 'German Bundesliga').split(',')
    if name.strip()
]
BETFAIR_MARKET_TYPES = [
    market_type.strip() for market_type in os.getenv('BETFAIR_MARKET_TYPES', 'MATCH_ODDS').split(',')
    if market_type.strip()
]
BETFAIR_MAX_MARKETS = int(os.getenv('BETFAIR_MAX_MARKETS', '30'))

# Configuración de apuestas
MIN_STAKE = float(os.getenv('MIN_STAKE', '1.0'))
MAX_STAKE = float(os.getenv('MAX_STAKE', '10.0'))
MIN_EDGE = float(os.getenv('MIN_EDGE', '0.05'))

# Intervalo de ejecución (segundos)
EXECUTION_INTERVAL = int(os.getenv('EXECUTION_INTERVAL', '10'))

# Configuración de evaluación de mercados
MINIMUM_BOOKMAKER_COUNT = int(os.getenv('MINIMUM_BOOKMAKER_COUNT', '3'))

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'betting_bot.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Encoding UTF-8 para el archivo de log
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',  # Usar stdout explícitamente
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'odds': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'betfair': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'betting': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_predictions': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'inspector': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
