# Generated by Django 4.2.7 on 2026-08-25 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True, verbose_name='API ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre API')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('type', models.CharField(choices=[('League', 'Liga'), ('Cup', 'Copa')], default='League', max_length=20, verbose_name='Tipo')),
                ('logo', models.URLField(blank=True, verbose_name='Logo')),
                ('kambi_path', models.CharField(blank=True, max_length=300, verbose_name='Path Kambi')),
                ('kambi_group', models.CharField(blank=True, max_length=200, verbose_name='Grupo BetPlay')),
                ('predicta_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Predicta')),
                ('predicta_league_id', models.IntegerField(blank=True, null=True, verbose_name='Liga Predicta (legacy)')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('has_statistics', models.BooleanField(default=False, verbose_name='Tiene estadísticas')),
                ('has_odds', models.BooleanField(default=False, verbose_name='Tiene cuotas')),
                ('has_predictions', models.BooleanField(default=False, verbose_name='Tiene predicciones')),
                ('seasons', models.JSONField(blank=True, default=list, verbose_name='Temporadas disponibles')),
                ('current_season', models.IntegerField(blank=True, null=True, verbose_name='Temporada actual')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioridad backfill')),
                ('backfill_status', models.CharField(choices=[('pending', 'Pendiente'), ('backfilling', 'Cargando'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado backfill')),
                ('last_backfill_at', models.DateTimeField(blank=True, null=True, verbose_name='Último backfill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liga API',
                'verbose_name_plural': 'Ligas API',
                'ordering': ['priority', 'country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApiTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True, verbose_name='API ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('logo', models.URLField(blank=True, verbose_name='Logo')),
                ('kambi_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre BetPlay')),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Nombre normalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo API',
                'verbose_name_plural': 'Equipos API',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('league_api_id', models.IntegerField(blank=True, null=True, verbose_name='Liga (API ID)')),
                ('season', models.IntegerField(blank=True, null=True, verbose_name='Temporada')),
                ('phase', models.CharField(blank=True, max_length=50, verbose_name='Fase')),
                ('cursor', models.JSONField(blank=True, default=dict, verbose_name='Cursor')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Corriendo'), ('paused', 'Pausado'), ('done', 'Hecho'), ('error', 'Error')], default='idle', max_length=20, verbose_name='Estado')),
                ('error_log', models.TextField(blank=True, verbose_name='Errores')),
                ('requests_today', models.IntegerField(default=0, verbose_name='Requests hoy')),
                ('limit_day', models.IntegerField(default=7500, verbose_name='Límite diario')),
                ('requests_remaining', models.IntegerField(default=7500, verbose_name='Requests restantes')),
                ('quota_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cuota')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última corrida')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de sincronización',
                'verbose_name_plural': 'Estados de sincronización',
            },
        ),
        migrations.CreateModel(
            name='ApiFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True, verbose_name='API ID')),
                ('season', models.IntegerField(verbose_name='Temporada')),
                ('round', models.CharField(blank=True, max_length=100, verbose_name='Jornada')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Fecha/hora')),
                ('status', models.CharField(db_index=True, max_length=10, verbose_name='Estado corto')),
                ('status_long', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Goles local')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Goles visitante')),
                ('ht_home', models.IntegerField(blank=True, null=True, verbose_name='HT local')),
                ('ht_away', models.IntegerField(blank=True, null=True, verbose_name='HT visitante')),
                ('ft_home', models.IntegerField(blank=True, null=True, verbose_name='FT local')),
                ('ft_away', models.IntegerField(blank=True, null=True, verbose_name='FT visitante')),
                ('et_home', models.IntegerField(blank=True, null=True, verbose_name='ET local')),
                ('et_away', models.IntegerField(blank=True, null=True, verbose_name='ET visitante')),
                ('pen_home', models.IntegerField(blank=True, null=True, verbose_name='Pen local')),
                ('pen_away', models.IntegerField(blank=True, null=True, verbose_name='Pen visitante')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Estadio')),
                ('referee', models.CharField(blank=True, max_length=200, verbose_name='Árbitro')),
                ('has_statistics', models.BooleanField(default=False, verbose_name='Tiene estadísticas')),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='Payload completo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='football_api.apiteam', verbose_name='Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='football_api.apiteam', verbose_name='Local')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='football_api.apileague', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Partido API',
                'verbose_name_plural': 'Partidos API',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeamFixtureStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots_on_goal', models.IntegerField(blank=True, null=True, verbose_name='Tiros a puerta')),
                ('shots_off_goal', models.IntegerField(blank=True, null=True, verbose_name='Tiros fuera')),
                ('total_shots', models.IntegerField(blank=True, null=True, verbose_name='Tiros totales')),
                ('blocked_shots', models.IntegerField(blank=True, null=True, verbose_name='Tiros bloqueados')),
                ('shots_insidebox', models.IntegerField(blank=True, null=True, verbose_name='Tiros dentro del área')),
                ('shots_outsidebox', models.IntegerField(blank=True, null=True, verbose_name='Tiros fuera del área')),
                ('fouls', models.IntegerField(blank=True, null=True, verbose_name='Faltas')),
                ('corner_kicks', models.IntegerField(blank=True, null=True, verbose_name='Córners')),
                ('offsides', models.IntegerField(blank=True, null=True, verbose_name='Fueras de juego')),
                ('ball_possession', models.CharField(blank=True, max_length=10, verbose_name='Posesión')),
                ('yellow_cards', models.IntegerField(blank=True, null=True, verbose_name='Amarillas')),
                ('red_cards', models.IntegerField(blank=True, null=True, verbose_name='Rojas')),
                ('goalkeeper_saves', models.IntegerField(blank=True, null=True, verbose_name='Atajadas')),
                ('total_passes', models.IntegerField(blank=True, null=True, verbose_name='Pases totales')),
                ('passes_accurate', models.IntegerField(blank=True, null=True, verbose_name='Pases precisos')),
                ('passes_pct', models.CharField(blank=True, max_length=10, verbose_name='Pases %')),
                ('expected_goals', models.FloatField(blank=True, null=True, verbose_name='xG')),
                ('goals_prevented', models.FloatField(blank=True, null=True, verbose_name='xG evitado (arquero)')),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='Payload completo')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='football_api.apifixture', verbose_name='Partido')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_stats', to='football_api.apiteam', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Estadística de partido',
                'verbose_name_plural': 'Estadísticas de partidos',
                'indexes': [models.Index(fields=['fixture'], name='football_ap_fixture_f94c9c_idx')],
                'unique_together': {('fixture', 'team')},
            },
        ),
        migrations.CreateModel(
            name='ApiOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=100, verbose_name='Casa de apuestas')),
                ('market', models.CharField(max_length=200, verbose_name='Mercado')),
                ('outcome', models.CharField(max_length=200, verbose_name='Selección')),
                ('odds', models.FloatField(verbose_name='Cuota')),
                ('line', models.FloatField(blank=True, null=True, verbose_name='Línea')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Capturada')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='football_api.apifixture', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Cuota API',
                'verbose_name_plural': 'Cuotas API',
                'indexes': [models.Index(fields=['fixture', 'market'], name='football_ap_fixture_cb71dd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apifixture',
            index=models.Index(fields=['league', 'season'], name='football_ap_league__98e952_idx'),
        ),
        migrations.AddIndex(
            model_name='apifixture',
            index=models.Index(fields=['status'], name='football_ap_status_09009a_idx'),
        ),
    ]
